llm:
  api_type: "gemini"
  api_key: "AIzaSyAzotTtutuw88IcWcekOom_4GtreG4GSNA"
  model: "gemini-pro"
  base_url: "https://ai.google.dev/"

mermaid:
  engine: "nodejs"
  path: "mmdc"
  puppeteer_config: "/app/metagpt/config/puppeteer-config.json"
  pyppeteer_path: "/usr/bin/chromium"